services:
  jarbas-app:
    build: .
    container_name: jarbas-app
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./memoria:/app/memoria
    ports:
      - "3000:3000"
    depends_on:
      - ollama
      - mqtt
    networks:
      - jarbas-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - jarbas-net

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - jarbas-net

networks:
  jarbas-net:
    driver: bridge

volumes:
  ollama_data:
