id: jarbas
name: Jarbas
version: "0.1.0"
description: Assistente pessoal local com IA com Ollama e MQTT via Docker
license: MIT
repository: https://github.com/seuusuario/jarbas-app

services:
  jarbas:
    name: Jarbas
    image: jarbas-app:latest   # ou "build" se preferir construir
    build:
      context: .
    container_name: jarbas
    environment:
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - memoria:/memoria
      - ./:/app
    ports:
      - 11436:11434
    depends_on:
      - ollama
      - mqtt

  ollama:
    name: Ollama
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - 11437:11434

  mqtt:
    name: MQTT Broker
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  memoria:
  ollama_data:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
